DDS=$1
echo "tail -n +2 ${DDS}_cli_serv_diff_topics.txt        | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_cli_serv_same_topics.txt        | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_default_clients_params_off.txt  | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_default_nodes.txt               | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_default_pubs_params_off.txt     | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_default_services_params_off.txt | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_default_subs_params_off.txt     | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_nodes_params_off.txt            | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_pub_sub_big_history_size.txt    | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_pub_sub_big_message_size.txt    | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_pub_sub_diff_msg_type.txt       | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_pub_sub_diff_topic.txt          | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"
echo "tail -n +2 ${DDS}_pub_sub_same_topic.txt          | rev | cut -c10- | rev | cut -c 30- | tr -d " \t\r" | xclip"

